### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by DanielFGray** [metakirby5/sanpai#2]
```
i:
    heard:
        you:
            like:
                yaml
```

Would it be possible to provide support for both yaml and toml? possibly also json? The more formats the better, I would think.

**Comment by metakirby5** [comment]
I think YAML is a superset of json, so that should already be supported (I may need to add .json to the list of recognised extensions). And as much as you know I disagree with toml, I know some people want to use it so I'm happy to support it :p

**Comment by metakirby5** [comment]
Hmm, after some more thought, I'm going to have to disagree with "the more formats the better." If more formats are supported, then the community's configuration files lose uniformity. This makes using another person's color sets a less pleasant experience, as then you'll either have to deal with a mix of toml and yaml files, or convert them yourself, which will only propagate the problem. I'm going to close this for now, but if you have any compelling arguments that you think I should put into consideration, let me know!
