### ISSUE TITLE
jinja2 expression syntax without  quotes

### ISSUE THREAD

**Issue by fullsalvo** [metakirby5/sanpai#4]
When using the `{{ variable }}` syntax without surrounding quotes when defining new variables in yamls, i.e.

```
foo:        {{ bar }}
```

it is interpreted as a dict, causing a yaml `ConstructorError` due to unacceptable formatting for dict keys.

This is simply fixed by adding quotes around the expression, `"{{ bar }}"` as opposed to how it is in the above example, but it's at the least somewhat unintuitive and perhaps a bit inconvenient.

**Comment by metakirby5** [comment]
Added a [wiki page](https://github.com/metakirby5/sanpai/wiki/Common-Gotchas).
