### ISSUE TITLE
variable type agreement

### ISSUE THREAD

**Issue by fullsalvo** [metakirby5/sanpai#5]
This is my fault, but in case it needs to be made clear when transitioning from whizkers, a major difference is that variables are inferred  to be a specific type when saved as a jinja variable as opposed to how they were used in mustache. As such, numeric variables must not be in quotes or they will be interpreted as strings, causing type errors when attempting mathematics using them.

tl;dr:
Yes: `number: 8`
No: `number: "8"`

**Comment by metakirby5** [comment]
Added a [wiki page](https://github.com/metakirby5/sanpai/wiki/Common-Gotchas).
